news_index:
    path:     /.{_format}
    defaults: { _controller: "DepartmentSiteNewsBundle:News:index" }
    methods:  GET

news_show:
    path:     /{id}/show.{_format}
    defaults: { _controller: "DepartmentSiteNewsBundle:News:show" }
    methods:  GET

news_new:
    path:     /new.{_format}
    defaults: { _controller: "DepartmentSiteNewsBundle:News:new" }
    methods:  [GET, POST]

news_edit:
    path:     /{id}/edit.{_format}
    defaults: { _controller: "DepartmentSiteNewsBundle:News:edit" }
    methods:  [GET, POST]

news_delete:
    path:     /{id}/delete.{_format}
    defaults: { _controller: "DepartmentSiteNewsBundle:News:delete" }
    methods:  DELETE
